name: microk8s-core-addons-offline
version: 'latest'
summary: MicroK8s Core addons offline
description: |
  Snap a demo configuration yaml file that MicroK8s can apply.
base: core18

grade: stable
confinement: strict

slots:
  configuration:
    interface: content
    content: configuration
    source:
      read:
        - $SNAP/launcher

parts:
  configuration:
    plugin: nil
    source: .
    override-build: |
      rm $SNAPCRAFT_PART_INSTALL/launcher -rf
      cp -rv launcher $SNAPCRAFT_PART_INSTALL/launcher
      (cd $SNAPCRAFT_PART_INSTALL/launcher/core-addons && git init && git add . && git commit -m 'test')
