kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gpu-operator
  labels:
    app.kubernetes.io/component: "gpu-operator"
    {{ $.Release.labels }}
subjects:
- kind: ServiceAccount
  name: gpu-operator
  namespace: {{ $.Release.Namespace }}
- kind: ServiceAccount
  name: node-feature-discovery
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gpu-operator
  apiGroup: rbac.authorization.k8s.io
