#!/bin/bash

. $SNAP/actions/common/utils.sh

touch $SNAP_DATA/var/lock/cni-loaded
rm $SNAP_DATA/args/cni-network/*

set_service_expected_to_start flanneld
restart_service containerd
restart_service flanneld

touch $SNAP_DATA/started_flannel
